# -*- coding: utf-8 -*-
"""Untitled26.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nWQFgrGn3OtDFRmikg-FhpFm4ljl_GU3
"""

import numpy as np
import pandas as pd
from tensorflow.keras.datasets import mnist

# Load MNIST data
(X_train, y_train), (_, _) = mnist.load_data()

# Pick a subset of images (e.g., 1000)
num_samples = 1000
X_subset = X_train[:num_samples]

# Flatten the 28x28 images into 784 columns
X_flat = X_subset.reshape(num_samples, -1)

# Save to CSV without labels
df = pd.DataFrame(X_flat)
df.to_csv("unlabeled_digits.csv", index=False, header=False)

print("✅ unlabeled_digits.csv generated.")

from google.colab import files
files.download('unlabeled_digits.csv')